use aiken/transaction/value.{AssetName, PolicyId}

pub const legacy_policy_id: PolicyId =
  #"f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a"

// LBL222 "pz_settings"
pub const pz_settings_asset_name: AssetName = #"000de140707a5f73657474696e6773"

// LBL222 "bg_policy_ids"
pub const bg_approver_asset_name: AssetName =
  #"000de14062675f706f6c6963795f696473"

// LBL222 "pfp_policy_ids"
pub const pfp_approver_asset_name: AssetName =
  #"000de1407066705f706f6c6963795f696473"
